refactor: :recycle: color set 적용
MediBird/caring-note-web pull request #34
Opened 2024-12-10 11:55 UTC by berrycracker5

- color set 적용
- svg 변환은 33 PR 승인 후 진행

2024-12-10 12:19 UTC, jawsbaek commented
font = weight 여서 이 부분도 체크 후 반영 부탁드려요

2024-12-10 12:20 UTC, jawsbaek requested changes
font 반영 부탁드립니디

2024-12-10 13:12 UTC, berrycracker5 commented
font 어디부분이용?

2024-12-12 01:58 UTC, jawsbaek commented
아 bold가 맞는 건가욤? 그러면 상관없을 것 같아여 머지 하시쟝

2024-12-12 01:58 UTC, jawsbaek approved these changes

2024-12-13 02:01 UTC, merged